language: r
cache: packages
sudo: false

# safelist
branches:
    only:
    - feat/add-travis

addons:
  apt:
    packages:
      - libxml2-dev
      - zlib1g-dev
      - libcurl4-openssl-dev
      - wget
      - python3.5

cache:
    directories:
    - $HOME/.local/share/renv
    - $TRAVIS_BUILD_DIR/renv/library

before_install:
    - pip3 --no-cache-dir install -r requirements.txt

install:
    - Rscript -e "install.packages('renv')"
    - Rscript -e "renv::consent(provided=TRUE)"
    - Rscript -e "renv::restore()"

script:
    "snakemake all --cores 1"