language: python
python:
    - 3.8
sudo: false

# safelist
branches:
    only:
    - feat/add-travis

addons:
  apt:
    packages:
      - software-properties-common  
      - libxml2-dev
      - zlib1g-dev
      - libcurl4-openssl-dev
      - wget
      - pandoc
      - gcc
    #   - python3-pip
    #   - python3.8

cache:
    directories:
    - $HOME/.local/share/renv
    - $TRAVIS_BUILD_DIR/renv/library

before_install:
    - sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/"
    - sudo apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'
    - sudo apt-get update
    - sudo apt install --allow-unauthenticated r-base
    # - pip3 install --upgrade setuptools pip
    - pip3 --no-cache-dir install -r requirements.txt

install:
    - Rscript -e "install.packages('renv')"
    - Rscript -e "renv::consent(provided=TRUE)"
    - Rscript -e "renv::restore()"
    - Rscript -e 'tinytex::install_tinytex()'
    - python3 --version

script:
    "snakemake all --cores 1"