language: r
sudo: false

# safelist
branches:
    only:
    - feat/add-travis

addons:
  apt:
    sources:
    - deadsnakes
    packages:
      - software-properties-common  
      - libxml2-dev
      - zlib1g-dev
      - libcurl4-openssl-dev
      - wget
      - python3.8
    #   - python3-pip

cache:
    directories:
    - $HOME/.local/share/renv
    - $TRAVIS_BUILD_DIR/renv/library

before_install:
    # - apt update
    # - apt install python3.8 python3-pip
    - pip3 install --upgrade setuptools pip
    - pip3 --no-cache-dir install -r requirements.txt

install:
    - Rscript -e "install.packages('renv')"
    - Rscript -e "renv::consent(provided=TRUE)"
    - Rscript -e "renv::restore()"
    - python3 --version

script:
    "snakemake all --cores 1"