ROOT: "."
src: "src/"
log: "logs/"
out: "out/"
src_data_mgt: "src/data-management/"
src_analysis: "src/analysis/"
src_final: "src/final/"
src_model_code: "src/model_code/"
src_model_specs: "src/model_specs/"
src_paper: "src/paper/"
src_data: "src/data/"
src_figures: "src/figures/"

out_analysis: "out/analysis/"
out_data: "out/data/"
out_figures: "out/figures/"
out_paper: "out/paper/"
out_tables: "out/tables/"
